export const projectsData = [
  {
    id: 1,
    name: "Minesweeper",
    technology: ["React Native"],
    url: "www.example.com",
    time: 8,
    type: "Game",
  },
  {
    id: 2,
    name: "Tic-Tac-Toe",
    technology: ["React JS", "CSS", "HTML", "JS"],
    url: "",
    time: 1,
    type: "Game",
  },
  {
    id: 3,
    name: "Trello Clone",
    technology: ["React JS", "CSS", "HTML", "JS"],
    url: "www.example.com",
    time: 8,
    type: "Utility",
  },
  {
    id: 4,
    name: "Dashboard",
    technology: ["React JS", "CSS", "HTML", "JS"],
    url: "www.example.com",
    time: 8,
    type: "Utility",
  },
  {
    id: 5,
    name: "Wordle",
    technology: ["React JS", "CSS", "HTML", "JS"],
    url: "www.example.com",
    time: 8,
    type: "Game",
  },
  {
    id: 6,
    name: "2048",
    technology: ["React Native"],
    url: "www.example.com",
    time: 8,
    type: "Game",
  },
];
